### PR TITLE
Add Dockerfile to test building in controlled way

### PR DESCRIPTION
**Pull request by epoz**
Hi @drobilla 

Thanks for sharing your library. I am hoping that it can be used to do some performant triple munging from Python, specifically for fixing things like malformed unescaped URIs in upstream data dumps.

Testing compilation, I get an error message:

```shell
7.871 [265/267] Generating serd.c with a custom command
7.871 FAILED: serd.c 
7.871 /data/bin/cython -3 --fast-fail -Wextra ../serd.pyx -o serd.c
7.871 warning: /data/serd.pyx:2475:35: Unknown type declaration 'uint' in annotation, ignoring
7.871 warning: /data/serd.pyx:2475:50: Unknown type declaration 'uint' in annotation, ignoring
7.871 
7.871 Error compiling Cython file:
7.871 ------------------------------------------------------------
7.871 ...
7.871     def __init__(self: Sink, world: World, func: callable = None):
7.871         if func is not None:
7.871             self._parent = world
7.871             self._env = Env(world)
7.871             self._func = func
7.871             self._ptr = serd_sink_new(NULL, <void*>self, Sink._c_on_event, NULL)
7.871                                                              ^
7.871 ------------------------------------------------------------
7.871 
7.871 /data/serd.pyx:2747:61: Cannot assign type 'SerdStatus (void *, const SerdEvent *) except *' to 'SerdEventFunc'
7.871 ninja: build stopped: subcommand failed.
```

Here is a Dockerfile that can be used for testing builds.

My C-fu is too weak to debug this one, do you have any suggestions on how to fix this build error please?

regards

@epoz

### CODE REVIEW

**Comment by drobilla** [comment]
Sorry, I don't recognize those particular errors, however, please see the README:

> A meson configuration is included that can fetch and build serd as a submodule, and build these bindings against that library, but this is intended for development and its use is unsupported.

I am not an expert in Python packaging, and especially not with cython generated bindings, but the meson build is just there as a sort of experiment and can be useful for integrating with other projects (if it works, which apparently it doesn't in whatever situation you're in).  Treat this as a normal cython package and use pip and/or setup.py, ignore the meson build unless you have some particular reason to use it, but in that case you're on your own.

**Comment by drobilla** [comment]
Ah, reproduced this problem:

> /data/serd.pyx:2747:61: Cannot assign type 'SerdStatus (void *, const SerdEvent *) except *' to 'SerdEventFunc'

Not sure what's going on though, the signatures seem to match and I'm pretty sure these revisions worked together at some point.  I'll look into it.

**Comment by drobilla** [comment]
Significant Python 3.11 breakage.

**Comment by epoz** [comment]
OK, thx for looking into it. Will try with a different Python version too.
I am not familiar with meson, hence adding a Dockerfile to try and make the build process testable for me.

**Comment by drobilla** [comment]
What platform are you on?

Issues should be fixed here: 3de61a8

Not sure about those casts, but it WFM and all the tests pass again at least.

**Comment by drobilla** [comment]
Whiiiiiiich broke the build on CI.  Sigh, Python...

**Comment by epoz** [comment]
Noting your comment about version-specific breakage, here is a as-plain-as-possible 3.9 Dockerfile.
This compiles, using the defaults, but when you try and run the tests it fails, not finding the libs.

Running `ldconfig` manually then fixes it, found Issue #15 referencing this too.

Am testing this with:
```
docker build -t python-serd .
and then
docker run --rm -it python-serd /bin/bash
```
(And then running python with and without the ldconfig inside the shell)

But for now, this is also "good enough" for me, as I can now run python-serd inside a container to get stuff done, without needing to install libs on the server.

Thanks for your efforts.

**Comment by drobilla** [comment]
Great.  I'll take note of the Dockerfile, although I'm not sure exactly what to do with that at the moment (there's already a CI setup, and it does build and run things in a general Docker image, but the above changes break that setup and so presumably break everything on older machines, blah blah, so I need to figure all of this out and see if the requirements have changed or if it's possible to have it work everywhere and all that)

**Pull request closed without merging**
